const MishapTable = [
    {id: 1, mishapname: "Spell Backfire", mishapeffect: "The caster takes 2d6 force damage as the spell rebounds."},
    {id: 2, mishapname: "Mana Surge", mishapeffect: "The caster's spellcasting ability score is reduced by 2 for 1 hour."},
    {id: 3, mishapname: "Wild Magic Surge", mishapeffect: "Roll on the Wild Magic Surge table (PHB p. 104)."},
    {id: 4, mishapname: "Disruption", mishapeffect: "The caster loses concentration, resulting in the loss of a spell they were concentrating on."},
    {id: 5, mishapname: "Misfire", mishapeffect: "The spell is cast but targets a random creature within 60 feet instead of the intended target."},
    {id: 6, mishapname: "Arcane Feedback", mishapeffect: "The caster suffers disadvantage on their next spell attack roll or saving throw within the next hour."},
    {id: 7, mishapname: "Sluggish Casting", mishapeffect: "The caster's movement speed is halved for the next minute due to lingering effects."},
    {id: 8, mishapname: "Elemental Drain", mishapeffect: "The caster loses 1d4 hit points as elemental energy surges unpredictably, siphoning their vitality."},
    {id: 9, mishapname: "Spell Confusion", mishapeffect: "The caster must roll a d4 on their next turn; on a roll of 1, they cast a random spell from their list."},
    {id: 10, mishapname: "Temporal Distortion", mishapeffect: "The caster is unable to cast spells for 1d4 rounds due to time distortion."},
    {id: 11, mishapname: "Spell Reflection", mishapeffect: "A reflected spell targets the caster, causing them to roll a saving throw to avoid its effects."},
    {id: 12, mishapname: "Counterspell Shock", mishapeffect: "The caster is stunned until the end of their next turn due to the backlash from an interrupted spell."},
    {id: 13, mishapname: "Unstable Magic", mishapeffect: "The caster suffers a surge of chaotic energy, causing them to roll 1d6 damage to themselves."},
    {id: 14, mishapname: "Aura of Confusion", mishapeffect: "All creatures within 10 feet must make a Wisdom saving throw or be confused for 1 minute."},
    {id: 15, mishapname: "Overloaded Spell", mishapeffect: "The caster must expend an additional spell slot of the same or higher level to complete the spell."},
    {id: 16, mishapname: "Elemental Misfire", mishapeffect: "The intended elemental effect changes (fire becomes ice, etc.), dealing 1d8 damage of that type to the caster."},
    {id: 17, mishapname: "Delayed Casting", mishapeffect: "The spell is delayed and activates at the start of the caster's next turn, affecting an unintended target."},
    {id: 18, mishapname: "Uncontrollable Energy", mishapeffect: "The caster releases a surge of wild magic, affecting all creatures in a 20-foot radius for 1d6 damage."},
    {id: 19, mishapname: "Arcane Burn", mishapeffect: "The caster suffers 1d8 fire damage from the backlash of their failed spell."},
    {id: 20, mishapname: "Magical Echo", mishapeffect: "The caster hears whispers of their spell's failure, imposing disadvantage on their next Wisdom check."},
    {id: 21, mishapname: "Spell Misalignment", mishapeffect: "The spell manifests, but it behaves in a completely opposite manner (healing instead of harming, etc.)."},
    {id: 22, mishapname: "Inverted Effects", mishapeffect: "The spell's intended effect is reversed, harming allies instead of enemies or vice versa."},
    {id: 23, mishapname: "Backlash of Elements", mishapeffect: "The caster suffers 1d6 damage of the spell's associated element (e.g., fire, cold)."},
    {id: 24, mishapname: "Fog of Confusion", mishapeffect: "A thick mist surrounds the caster, imposing disadvantage on all attack rolls for 1 minute."},
    {id: 25, mishapname: "Force of Nature", mishapeffect: "The caster is knocked prone by a sudden gust of wind as nature reacts to the failed magic."},
    {id: 26, mishapname: "Magic Drain", mishapeffect: "The caster loses 1d4 spell slots of their choice, which cannot be recovered until a long rest."},
    {id: 27, mishapname: "Chaotic Effect", mishapeffect: "Roll 1d10 for a random effect from the following: 1) gain a random cantrip, 2) lose a random spell, etc."},
    {id: 28, mishapname: "Lingering Effects", mishapeffect: "The caster must make a Constitution saving throw or be poisoned for 1d4 rounds."},
    {id: 29, mishapname: "Reversed Runes", mishapeffect: "The caster is marked with a glowing rune that attracts unwanted attention for 1 hour."},
    {id: 30, mishapname: "Mana Storm", mishapeffect: "A burst of magical energy deals 1d10 force damage to all creatures within 30 feet."},
    {id: 31, mishapname: "Spell Flicker", mishapeffect: "The spell appears to succeed but flickers, failing to take effect and causing confusion."},
    {id: 32, mishapname: "Energy Feedback", mishapeffect: "The caster's next spell is cast with disadvantage due to residual energy."},
    {id: 33, mishapname: "Summon Unwanted Ally", mishapeffect: "An unintended creature appears and attacks the caster, acting on its own initiative."},
    {id: 34, mishapname: "Area of Silence", mishapeffect: "An area around the caster becomes silent for 1 minute, preventing any verbal spells."},
    {id: 35, mishapname: "Chaotic Blast", mishapeffect: "The caster's failed spell explodes, dealing 2d6 damage in a 15-foot radius."},
    {id: 36, mishapname: "Shadow of Doubt", mishapeffect: "The caster must succeed on a Wisdom saving throw or have disadvantage on their next three rolls."},
    {id: 37, mishapname: "Dimensional Drift", mishapeffect: "The caster is randomly teleported 1d10 feet in a random direction."},
    {id: 38, mishapname: "Arcane Misfire", mishapeffect: "The spell causes a magical explosion that knocks everyone prone within 10 feet."},
    {id: 39, mishapname: "Visions of Failure", mishapeffect: "The caster is frightened for 1 minute by haunting visions of their failure."},
    {id: 40, mishapname: "Spell Interference", mishapeffect: "All spellcasting within 30 feet is disrupted for the next turn, causing confusion among casters."},
    {id: 41, mishapname: "Concentration Loss", mishapeffect: "The caster must roll a Constitution saving throw or lose concentration on all spells currently active."},
    {id: 42, mishapname: "Sudden Fatigue", mishapeffect: "The caster gains 1 level of exhaustion due to the mental strain of the failed spell."},
    {id: 43, mishapname: "Arcane Short Circuit", mishapeffect: "The caster's spell fails spectacularly, causing them to take 1d4 lightning damage."},
    {id: 44, mishapname: "Corrupted Magic", mishapeffect: "The caster's spells now require an additional component for the next hour, as the magic feels tainted."},
    {id: 45, mishapname: "Unstable Manifestation", mishapeffect: "A random spell effect occurs from the caster's previous spell, impacting all creatures within 15 feet."},
    {id: 46, mishapname: "Forced Rewind", mishapeffect: "The caster is compelled to repeat the failed spell, but at a higher level, if possible."},
    {id: 47, mishapname: "Mystic Jinx", mishapeffect: "The caster must roll a d20 for all ability checks until the end of their next turn."},
    {id: 48, mishapname: "Temporary Blindness", mishapeffect: "The caster is blinded for 1d4 rounds as a result of a magic misfire."},
    {id: 49, mishapname: "Transmutation Error", mishapeffect: "The caster’s body temporarily transforms, imposing disadvantage on physical rolls for 1 hour."},
    {id: 50, mishapname: "Chaotic Companion", mishapeffect: "A familiar or creature from the astral plane appears, confused and hostile for 1d6 rounds."},
    {id: 51, mishapname: "Hex of Confusion", mishapeffect: "The caster is cursed, imposing disadvantage on all Intelligence checks for 1 hour."},
    {id: 52, mishapname: "Illusory Duplicates", mishapeffect: "The caster creates 1d4 illusory duplicates of themselves, causing confusion for enemies, but all must make a saving throw."},
    {id: 53, mishapname: "Siphoned Energy", mishapeffect: "The caster must roll 1d8, losing that many hit points due to magical backlash."},
    {id: 54, mishapname: "Vortex of Energy", mishapeffect: "The caster is pulled 10 feet toward the nearest creature as magic pulls them in."},
    {id: 55, mishapname: "Overexertion", mishapeffect: "The caster suffers disadvantage on Constitution saving throws until the end of their next long rest."},
    {id: 56, mishapname: "Ill-fated Blessing", mishapeffect: "All allies within 30 feet must succeed on a saving throw or take 1d6 psychic damage from the caster's failure."},
    {id: 57, mishapname: "Wild Magic Flare", mishapeffect: "A random magical effect occurs within 30 feet of the caster, affecting everyone randomly."},
    {id: 58, mishapname: "Eldritch Whisper", mishapeffect: "The caster hears a dark voice, imposing disadvantage on all Wisdom saving throws for 1 hour."},
    {id: 59, mishapname: "Vulnerability", mishapeffect: "The caster gains vulnerability to the next type of damage they take for the next hour."},
    {id: 60, mishapname: "Dimensional Displacement", mishapeffect: "The caster is momentarily displaced, causing them to take an extra turn at the end of the current initiative."},
    {id: 61, mishapname: "Mystical Disruption", mishapeffect: "All spells within 30 feet of the caster are disrupted, forcing all nearby casters to roll a saving throw."},
    {id: 62, mishapname: "Aura of Mistrust", mishapeffect: "The caster emanates an aura causing all creatures within 10 feet to distrust them, imposing disadvantage on Charisma checks."},
    {id: 63, mishapname: "Distorted Reality", mishapeffect: "The caster experiences hallucinations, imposing disadvantage on their next Intelligence check."},
    {id: 64, mishapname: "Temporal Rewind", mishapeffect: "The caster is forced to repeat the last action taken in combat, regardless of the outcome."},
    {id: 65, mishapname: "Chaotic Resonance", mishapeffect: "The caster resonates with chaotic magic, attracting hostile creatures within 30 feet for 1 round."},
    {id: 66, mishapname: "Hexed Circle", mishapeffect: "The area around the caster becomes cursed for 1d6 rounds, affecting allies with disadvantage on saving throws."},
    {id: 67, mishapname: "Magical Shortage", mishapeffect: "The caster's available spell slots are reduced by one level for the next long rest."},
    {id: 68, mishapname: "Mental Exhaustion", mishapeffect: "The caster takes 1d4 psychic damage due to the mental toll of failing their spell."},
    {id: 69, mishapname: "Aura of Confusion", mishapeffect: "Allies within 10 feet must succeed on a Wisdom saving throw or be confused for 1 minute."},
    {id: 70, mishapname: "Arcane Recoil", mishapeffect: "The caster's next spell is cast at one level higher than intended, consuming an additional spell slot."},
    {id: 71, mishapname: "Misguided Intent", mishapeffect: "The spell’s effects are misapplied, causing friendly fire or unintended consequences for allies."},
    {id: 72, mishapname: "Energy Exchange", mishapeffect: "The caster swaps hit points with the nearest creature within 30 feet, causing mutual damage."},
    {id: 73, mishapname: "Binding Chain", mishapeffect: "The caster is magically restrained for 1d4 rounds due to the backlash of their spell."},
    {id: 74, mishapname: "Corrupted Spell Components", mishapeffect: "The caster's spell components become unusable until they take a short or long rest to recover."},
    {id: 75, mishapname: "Unexpected Transformation", mishapeffect: "The caster undergoes a random physical transformation for 1d6 hours, altering their appearance."},
    {id: 76, mishapname: "Fickle Fate", mishapeffect: "The caster must roll a d20 for each spell they cast in the next hour; on a roll of 1, the spell fails."},
    {id: 77, mishapname: "Negative Energy Surge", mishapeffect: "The caster takes 2d4 necrotic damage as the magic siphons their life force."},
    {id: 78, mishapname: "Illusionary Banter", mishapeffect: "The caster hears mocking voices, imposing disadvantage on Charisma checks for 1 hour."},
    {id: 79, mishapname: "Tethered Spirits", mishapeffect: "Spirits are drawn to the caster, imposing disadvantage on Wisdom saving throws for 1 hour."},
    {id: 80, mishapname: "Elemental Echo", mishapeffect: "The caster creates an elemental echo that briefly manifests, dealing 1d6 damage to themselves."},
    {id: 81, mishapname: "Keen Insight", mishapeffect: "The caster must reveal a personal secret to everyone within 30 feet or take psychic damage equal to their level."},
    {id: 82, mishapname: "Mana Corruption", mishapeffect: "The caster's next spell requires an additional material component to succeed."},
    {id: 83, mishapname: "Phantom Grasp", mishapeffect: "The caster is magically restrained by ethereal hands for 1 round."},
    {id: 84, mishapname: "Detrimental Residue", mishapeffect: "The caster's body is covered in a sticky residue, reducing their movement speed by half for 1 hour."},
    {id: 85, mishapname: "Cursed Relic", mishapeffect: "A cursed item appears in the caster's possession, imposing a disadvantage on specific rolls until it is removed."},
    {id: 86, mishapname: "Cacophony of Voices", mishapeffect: "The caster hears multiple voices, imposing disadvantage on Wisdom saving throws for 1 hour."},
    {id: 87, mishapname: "Siphoned Luck", mishapeffect: "The caster suffers disadvantage on all saving throws until they complete a short rest."},
    {id: 88, mishapname: "Echo of Despair", mishapeffect: "The caster becomes aware of a past failure, imposing disadvantage on all skill checks for 1 hour."},
    {id: 89, mishapname: "Divine Retribution", mishapeffect: "The caster takes 2d4 radiant damage as divine energy backlash punishes their failure."},
    {id: 90, mishapname: "Crimson Mark", mishapeffect: "The caster gains a visible mark that attracts enemies, imposing disadvantage on stealth checks for 1 hour."},
    {id: 91, mishapname: "Spell Fatigue", mishapeffect: "The caster suffers a -2 penalty to all spell attacks until they take a short rest."},
    {id: 92, mishapname: "Sudden Reversal", mishapeffect: "The caster is forced to take the Dash action away from the nearest enemy on their next turn."},
    {id: 93, mishapname: "Waning Magic", mishapeffect: "The caster's spells require an extra action to cast for the next hour due to magical fatigue."},
    {id: 94, mishapname: "Muddled Thoughts", mishapeffect: "The caster must succeed on an Intelligence saving throw or become confused for 1 round."},
    {id: 95, mishapname: "Ethereal Flicker", mishapeffect: "The caster flickers in and out of reality, causing disadvantage on attacks for 1d4 rounds."},
    {id: 96, mishapname: "Soul Link", mishapeffect: "The caster links their soul with a random ally; if one takes damage, the other takes half that damage."},
    {id: 97, mishapname: "Illusory Target", mishapeffect: "An illusory copy of the caster appears, drawing attacks and causing confusion for enemies."},
    {id: 98, mishapname: "Chilling Presence", mishapeffect: "The caster radiates a cold aura, imposing disadvantage on saving throws against fear for 1 hour."},
    {id: 99, mishapname: "Whispering Shadows", mishapeffect: "Shadows gather around the caster, imposing disadvantage on all stealth checks for 1 hour."},
    {id: 100, mishapname: "Phantom Pain", mishapeffect: "The caster experiences excruciating pain, imposing disadvantage on all attack rolls for 1d4 rounds."},
    {id: 101, mishapname: "Delayed Reaction", mishapeffect: "The caster’s spell is delayed by one full round and affects a random target."},
    {id: 102, mishapname: "Echoed Incantations", mishapeffect: "The last spell the caster cast reactivates on a random target within range."},
    {id: 103, mishapname: "Reality Rip", mishapeffect: "A tear in reality opens, summoning a random creature (CR 1 or lower) for 1 minute, hostile to all."},
    {id: 104, mishapname: "Spectral Grasp", mishapeffect: "The caster is restrained by ghostly hands until they succeed on a DC 15 Strength check."},
    {id: 105, mishapname: "Mana Drain", mishapeffect: "The caster loses half of their spell slots for the rest of the day."},
    {id: 106, mishapname: "Corrosive Mana", mishapeffect: "The caster’s spellcasting focus is partially damaged, imposing disadvantage on spell attack rolls for 1 hour."},
    {id: 107, mishapname: "Arcane Rebound", mishapeffect: "The caster takes 2d6 force damage, and the next spell cast within 1 minute is cast at disadvantage."},
    {id: 108, mishapname: "Brittle Bones", mishapeffect: "The caster’s AC is reduced by 1d4 for 10 minutes as they feel their bones weaken."},
    {id: 109, mishapname: "Unintended Binding", mishapeffect: "A magical tether binds the caster to the closest creature within 20 feet for 1 minute."},
    {id: 110, mishapname: "Overwhelming Fragrance", mishapeffect: "A floral scent fills the air, charming all within 10 feet, who have disadvantage on Wisdom saves."},
    {id: 111, mishapname: "Echo of Power", mishapeffect: "The caster’s voice booms uncontrollably, imposing disadvantage on Stealth checks for 10 minutes."},
    {id: 112, mishapname: "Curse of Silence", mishapeffect: "The caster is silenced for 1d4 rounds, unable to verbally cast spells or speak."},
    {id: 113, mishapname: "Planar Glimpse", mishapeffect: "The caster has a vision of another plane, causing disadvantage on all Perception checks for 1 hour."},
    {id: 114, mishapname: "Temporal Shift", mishapeffect: "The caster ages 1d4 years instantly, with no immediate effect but visible changes in appearance."},
    {id: 115, mishapname: "Mana Riptide", mishapeffect: "The caster is pushed back 10 feet by a wave of magical energy."},
    {id: 116, mishapname: "Chilling Glare", mishapeffect: "The caster’s eyes glow, causing creatures within 10 feet to make a DC 13 Wisdom save or be frightened."},
    {id: 117, mishapname: "Doppelganger’s Shadow", mishapeffect: "A shadowy figure resembling the caster appears and mimics their movements for 1 minute."},
    {id: 118, mishapname: "Arcane Burst", mishapeffect: "A burst of magic knocks back all creatures within 5 feet, dealing 1d6 force damage."},
    {id: 119, mishapname: "Ether’s Laughter", mishapeffect: "The caster hears laughter from beyond, imposing disadvantage on Charisma checks for 1 hour."},
    {id: 120, mishapname: "Ethereal Shift", mishapeffect: "The caster becomes partially ethereal, suffering disadvantage on physical interactions for 1 minute."},
    {id: 121, mishapname: "Creeping Vines", mishapeffect: "Magic conjures vines around the caster’s legs, reducing their movement speed by half for 1 minute."},
    {id: 122, mishapname: "Surge of Warmth", mishapeffect: "The caster’s skin glows warmly, revealing their position and granting advantage to attackers for 1 turn."},
    {id: 123, mishapname: "Web of Madness", mishapeffect: "The caster feels haunted, suffering disadvantage on all Wisdom saves for the next 10 minutes."},
    {id: 124, mishapname: "Eerie Music", mishapeffect: "Unseen music plays around the caster, unsettling creatures within 20 feet for 1 minute."},
    {id: 125, mishapname: "Magic Drainer", mishapeffect: "The caster loses the ability to cast spells for 1d6 rounds."},
    {id: 126, mishapname: "Random Teleportation", mishapeffect: "The caster teleports 10 feet in a random direction, potentially into hazardous areas."},
    {id: 127, mishapname: "Misaligned Senses", mishapeffect: "The caster’s senses become jumbled, giving them disadvantage on Perception checks for 1d4 hours."},
    {id: 128, mishapname: "Arcane Radiation", mishapeffect: "The caster glows faintly for 1 hour, imposing disadvantage on Stealth checks."},
    {id: 129, mishapname: "Visions of Horror", mishapeffect: "The caster sees horrifying visions, gaining the frightened condition for 1 minute."},
    {id: 130, mishapname: "Energy Feedback Loop", mishapeffect: "The spell loops back on the caster, who must repeat the spell every turn for 1d4 rounds."},
    {id: 131, mishapname: "Volatile Magic Field", mishapeffect: "The area within 10 feet of the caster becomes volatile, dealing 1d4 damage per round to anyone in it."},
    {id: 132, mishapname: "Sudden Cold Snap", mishapeffect: "The temperature around the caster drops, slowing their movement by 10 feet for 1 minute."},
    {id: 133, mishapname: "Phantasmal Bite", mishapeffect: "The caster feels an invisible bite, taking 1d8 psychic damage."},
    {id: 134, mishapname: "Mirage of Failure", mishapeffect: "The caster sees illusions of themselves failing, imposing disadvantage on their next two rolls."},
    {id: 135, mishapname: "Spell Reflect", mishapeffect: "The caster’s spell rebounds, affecting them as if they were the original target."},
    {id: 136, mishapname: "Lost Thoughts", mishapeffect: "The caster forgets the spell they attempted to cast and must relearn it before casting again."},
    {id: 137, mishapname: "Gravity Flux", mishapeffect: "Gravity around the caster shifts for 1 minute, causing all creatures within 20 feet to make Dexterity saves."},
    {id: 138, mishapname: "Infernal Whisper", mishapeffect: "A faint whisper plagues the caster, imposing disadvantage on Wisdom saving throws for 10 minutes."},
    {id: 139, mishapname: "Temporal Reflection", mishapeffect: "The caster sees a future self, disoriented and distracted, taking disadvantage on their next roll."},
    {id: 140, mishapname: "Phantasmal Shadow", mishapeffect: "A shadowy creature appears within 5 feet of the caster, ignoring others and following them for 1 minute."},
    {id: 141, mishapname: "Thunderous Echo", mishapeffect: "The spell’s failure resonates, causing a loud boom audible up to 300 feet."},
    {id: 142, mishapname: "Blinding Light", mishapeffect: "A flash blinds the caster for 1 round."},
    {id: 143, mishapname: "Blood Pact", mishapeffect: "The caster takes 1d10 necrotic damage as they accidentally bind themselves to a foreign entity."},
    {id: 144, mishapname: "Mage’s Mark", mishapeffect: "A magical glyph appears on the caster’s forehead, identifiable by any creature that can see magic."},
    {id: 145, mishapname: "Electric Tingle", mishapeffect: "The caster takes 1d6 lightning damage as static energy crackles around them."},
    {id: 146, mishapname: "Temporal Lag", mishapeffect: "The caster’s next turn is delayed to the end of the initiative order."},
    {id: 147, mishapname: "Reverse Gravity", mishapeffect: "For 1 round, gravity is reversed for the caster, pulling them 10 feet into the air."},
    {id: 148, mishapname: "Searing Heat", mishapeffect: "The area around the caster warms rapidly, causing disadvantage on Constitution saving throws."},
    {id: 149, mishapname: "Darkened Vision", mishapeffect: "Shadows cloud the caster’s sight, imposing disadvantage on all Perception checks for 1d6 hours."},
    {id: 150, mishapname: "Ethereal Sickness", mishapeffect: "The caster feels nauseous, gaining the poisoned condition for 1 minute."},
    {id: 151, mishapname: "Bubble of Isolation", mishapeffect: "The caster is trapped inside an unbreakable, transparent bubble for 1 minute. They can’t cast spells or attack."},
    {id: 152, mishapname: "Inflation Jinx", mishapeffect: "The caster begins to inflate like a balloon, rising 5 feet in the air. Movement is reduced to 5 feet for 1 hour."},
    {id: 153, mishapname: "Swarm of Butterflies", mishapeffect: "A cloud of butterflies surrounds the caster, obscuring vision and imposing disadvantage on attacks for 1 minute."},
    {id: 154, mishapname: "Spontaneous Combustion", mishapeffect: "The caster emits smoke and sparks. They take 1d4 fire damage every turn for 1 minute unless doused in water."},
    {id: 155, mishapname: "Reverse Aging", mishapeffect: "The caster physically regresses in age by 10 years, though they retain their abilities. The effect lasts 1 hour."},
    {id: 156, mishapname: "Chattering Teeth", mishapeffect: "The caster’s teeth begin chattering uncontrollably, giving them disadvantage on all verbal spellcasting rolls."},
    {id: 157, mishapname: "Random Rhyme Compulsion", mishapeffect: "For the next 10 minutes, the caster can only speak in rhyme. Failure to rhyme deals 1 psychic damage each time."},
    {id: 158, mishapname: "Extra Limbs", mishapeffect: "The caster grows an extra pair of arms, which flail wildly, giving disadvantage on Dexterity checks for 1 hour."},
    {id: 159, mishapname: "Floral Explosion", mishapeffect: "The caster’s hair transforms into blooming flowers, which attract insects and impose disadvantage on Stealth."},
    {id: 160, mishapname: "Sticky Skin", mishapeffect: "The caster’s skin becomes sticky, making it difficult to handle objects. Disadvantage on all item interactions."},
    {id: 161, mishapname: "Backwards Speech", mishapeffect: "The caster can only speak backward for the next 1d4 hours, which affects spellcasting and communication."},
    {id: 162, mishapname: "Big Head Syndrome", mishapeffect: "The caster’s head inflates, doubling in size, and giving them disadvantage on Intelligence checks for 1 hour."},
    {id: 163, mishapname: "Random Aroma", mishapeffect: "The caster smells strongly of fish for the next hour, giving nearby creatures advantage on Perception checks."},
    {id: 164, mishapname: "Feline Fascination", mishapeffect: "Cats within a 100-foot radius are irresistibly drawn to the caster, following and meowing loudly for 1 hour."},
    {id: 165, mishapname: "Cacophony of Laughter", mishapeffect: "The caster hears loud laughter in their head, giving them disadvantage on all Wisdom saves for 1d4 minutes."},
    {id: 166, mishapname: "Limb Swapping", mishapeffect: "The caster’s arms and legs swap places, halving movement and giving disadvantage on Strength checks for 1 hour."},
    {id: 167, mishapname: "Miniature Duplicate", mishapeffect: "A tiny duplicate of the caster appears, echoing all their actions and giving disadvantage on all Stealth rolls."},
    {id: 168, mishapname: "Temporary Transparency", mishapeffect: "The caster turns semi-transparent, imposing disadvantage on Charisma checks as they become unnerving to others."},
    {id: 169, mishapname: "Flaming Footprints", mishapeffect: "The caster’s footprints leave small flames, dealing 1 fire damage to creatures who step in them for 1 minute."},
    {id: 170, mishapname: "Gravity Flip", mishapeffect: "The caster’s gravity is inverted for 1 minute, causing them to float 10 feet in the air. Requires concentration to stay grounded."},
    {id: 171, mishapname: "Raging Rageberries", mishapeffect: "The caster sprouts berry-like growths on their body that pop and stain, giving disadvantage on Dexterity checks."},
    {id: 172, mishapname: "Sudden Beard Growth", mishapeffect: "Regardless of gender, the caster grows a large, unruly beard, which impedes vision and Dexterity for 1 hour."},
    {id: 173, mishapname: "Jelly Limbs", mishapeffect: "The caster’s limbs lose structure, becoming floppy and unusable for 1 minute, halving speed and strength."},
    {id: 174, mishapname: "Puddle Form", mishapeffect: "The caster turns into a small puddle of water for 1d4 rounds. They can’t act but are immune to physical damage."},
    {id: 175, mishapname: "Invisible Companions", mishapeffect: "The caster believes they are surrounded by invisible allies, giving disadvantage on all Insight checks for 1 hour."},
    {id: 176, mishapname: "Polka Dot Pattern", mishapeffect: "The caster’s skin is covered in brightly colored polka dots for 24 hours, causing disadvantage on Stealth rolls."},
    {id: 177, mishapname: "Unwanted Dance", mishapeffect: "The caster uncontrollably dances for 1d4 rounds, unable to take any other actions."},
    {id: 178, mishapname: "Melodic Echo", mishapeffect: "Every word the caster says echoes musically for 1 hour, imposing disadvantage on Stealth and spellcasting."},
    {id: 179, mishapname: "Feather Weight", mishapeffect: "The caster’s weight reduces to almost nothing, allowing them to be knocked back 10 feet with any impact."},
    {id: 180, mishapname: "Floating Halo", mishapeffect: "A glowing halo appears above the caster’s head, illuminating 10 feet but giving disadvantage on Stealth checks."},
    {id: 181, mishapname: "Overgrowth", mishapeffect: "Moss and vines start growing on the caster’s skin, halving their movement speed for 1d6 hours."},
    {id: 182, mishapname: "Talking Hands", mishapeffect: "The caster’s hands develop mouths and begin chattering incessantly, imposing disadvantage on Stealth checks."},
    {id: 183, mishapname: "Exploding Shoes", mishapeffect: "The caster’s shoes explode with confetti, destroying footwear and imposing disadvantage on movement for 1 hour."},
    {id: 184, mishapname: "Shadow Swap", mishapeffect: "The caster’s shadow becomes independent and mimics them, distracting and imposing disadvantage on Perception."},
    {id: 185, mishapname: "Glowing Green", mishapeffect: "The caster glows an eerie green, lighting a 15-foot radius but attracting unwanted attention for 1 hour."},
    {id: 186, mishapname: "Egg-laying Spell", mishapeffect: "The caster lays a large, fragile egg. Breaking it releases a harmless but embarrassing magical spark."},
    {id: 187, mishapname: "Reverse Gravity Hair", mishapeffect: "The caster’s hair floats straight up, creating a wild look and giving disadvantage on Charisma checks."},
    {id: 188, mishapname: "Fish Breath", mishapeffect: "The caster’s breath smells like fish, causing disadvantage on Persuasion checks for 1d4 hours."},
    {id: 189, mishapname: "Inverted Vision", mishapeffect: "The caster’s vision flips upside down for 10 minutes, giving disadvantage on all Dexterity checks."},
    {id: 190, mishapname: "Ghostly Voice", mishapeffect: "The caster’s voice becomes ghostly and faint, imposing disadvantage on verbal spellcasting."},
    {id: 191, mishapname: "Extra Fingers", mishapeffect: "The caster grows extra fingers on each hand, giving disadvantage on Dexterity-based checks for 1 hour."},
    {id: 192, mishapname: "Itchy Sparks", mishapeffect: "Tiny sparks of magic itch uncontrollably on the caster’s skin, imposing disadvantage on concentration checks."},
    {id: 193, mishapname: "Rotating Nose", mishapeffect: "The caster’s nose spins uncontrollably, giving disadvantage on all Perception checks using smell."},
    {id: 194, mishapname: "Flame Tongue", mishapeffect: "The caster’s tongue ignites briefly when they speak, dealing 1 fire damage each time they cast a spell."},
    {id: 195, mishapname: "Bubble Burp", mishapeffect: "Each time the caster speaks, a small bubble floats out of their mouth, imposing disadvantage on Stealth."},
    {id: 196, mishapname: "Glued Feet", mishapeffect: "The caster’s feet stick to the ground for 1d4 rounds, halving their movement speed until they break free."},
    {id: 197, mishapname: "Insect Attraction", mishapeffect: "Harmless insects swarm the caster, imposing disadvantage on Perception and Charisma checks for 1 hour."},
    {id: 198, mishapname: "Mirror Clone", mishapeffect: "A mirror clone of the caster appears, repeating their every move and causing confusion for 1 minute."},
    {id: 199, mishapname: "Scent of Cinnamon", mishapeffect: "The caster exudes a strong cinnamon aroma, which attracts animals and gives disadvantage on Stealth checks."},
    {id: 200, mishapname: "Inexplicable Nausea", mishapeffect: "The caster feels suddenly queasy, gaining the poisoned condition for 1 minute."},
    {id: 201, mishapname: "Blood Boil", mishapeffect: "The caster’s blood heats up, dealing 1d6 fire damage every round for 1 minute unless they succeed on a DC 15 Constitution saving throw each turn."},
    {id: 202, mishapname: "Lingering Echoes", mishapeffect: "The caster is haunted by faint whispers for 1d4 hours, causing disadvantage on all Wisdom and Perception checks."},
    {id: 203, mishapname: "Soul Fragment", mishapeffect: "A piece of the caster’s soul is briefly severed, reducing their hit point maximum by 5 until they complete a long rest."},
    {id: 204, mishapname: "Spectral Embrace", mishapeffect: "Ghostly hands reach out to clutch the caster, reducing their movement speed by half and imposing disadvantage on Dexterity saving throws for 10 minutes."},
    {id: 205, mishapname: "Shadowed Vision", mishapeffect: "The caster’s vision is dimmed by a shadowy haze, giving disadvantage on all sight-based Perception checks for 1 hour."},
    {id: 206, mishapname: "Unholy Mark", mishapeffect: "A dark symbol appears on the caster’s forehead, alerting undead within 100 feet to their presence for 1d4 hours."},
    {id: 207, mishapname: "Graveyard Chill", mishapeffect: "A cold, deathly chill surrounds the caster, giving them disadvantage on all Constitution saves and reducing movement speed by 10 feet for 1 hour."},
    {id: 208, mishapname: "Corpse Scent", mishapeffect: "The caster’s body emits a foul odor of decay, imposing disadvantage on all Charisma checks for 1d6 hours."},
    {id: 209, mishapname: "Draining Veins", mishapeffect: "The caster’s veins pulse with dark energy, causing them to lose 1 hit point every turn for the next minute."},
    {id: 210, mishapname: "Lurking Eyes", mishapeffect: "The caster feels constantly watched, giving disadvantage on all Insight and Perception checks for 8 hours."},
    {id: 211, mishapname: "Decay Touch", mishapeffect: "Anything the caster touches begins to rot slightly, giving disadvantage on all Dexterity-based checks involving objects. This lasts for 10 minutes."},
    {id: 212, mishapname: "Spirit Binding", mishapeffect: "The caster becomes bound to an unseen spirit, who whispers their deepest fears, causing disadvantage on Wisdom checks for 1d4 hours."},
    {id: 213, mishapname: "Eyes of the Dead", mishapeffect: "The caster temporarily sees through the eyes of a deceased creature nearby, rendering them blind to their own surroundings for 1 minute."},
    {id: 214, mishapname: "Haunted Aura", mishapeffect: "Ghostly apparitions hover around the caster, causing any creature within 10 feet to feel uneasy and imposing disadvantage on Charisma checks for 1 hour."},
    {id: 215, mishapname: "Blood Pact", mishapeffect: "A small cut appears on the caster’s hand, leaking blood that won’t stop until a Healing spell is cast, dealing 1 damage per minute."},
    {id: 216, mishapname: "Curse of Isolation", mishapeffect: "The caster feels a supernatural aversion to others, giving them disadvantage on all group-based Skill Checks and Charisma checks for 1d4 hours."},
    {id: 217, mishapname: "Raven’s Shadow", mishapeffect: "A shadow resembling a raven follows the caster, making them feel cursed. They have disadvantage on Wisdom saves for 1 hour."},
    {id: 218, mishapname: "Spirit Shackles", mishapeffect: "Invisible shackles bind the caster, reducing movement speed by half for 1 minute. They can’t Dash during this time."},
    {id: 219, mishapname: "Voice of the Damned", mishapeffect: "The caster’s voice takes on an eerie, guttural tone, causing disadvantage on Persuasion checks and drawing the attention of nearby undead."},
    {id: 220, mishapname: "Unseen Stalker", mishapeffect: "The caster becomes convinced they’re being followed by an invisible entity, imposing disadvantage on Perception checks for 1 hour."},
    {id: 221, mishapname: "Withering Touch", mishapeffect: "The caster’s touch becomes necrotic, dealing 1d6 necrotic damage to anything they handle, including allies, for 10 minutes."},
    {id: 222, mishapname: "Rotting Glare", mishapeffect: "For 1 minute, the caster’s gaze causes small plants around them to wither, imposing disadvantage on Charisma checks as they appear cursed."},
    {id: 223, mishapname: "Eldritch Claws", mishapeffect: "The caster’s hands contort into claw-like forms, giving them disadvantage on Dexterity checks and reducing attack roll accuracy for 1d4 hours."},
    {id: 224, mishapname: "Scent of Death", mishapeffect: "The caster emanates the smell of death, causing creatures within 10 feet to make a DC 13 Constitution save or be poisoned for 1 hour."},
    {id: 225, mishapname: "Vampiric Surge", mishapeffect: "The caster feels a deep thirst for blood, imposing disadvantage on all attack rolls against non-living targets for 1d4 hours."},
    {id: 226, mishapname: "Twilight Shift", mishapeffect: "Shadows cling to the caster, making them harder to see in light but giving disadvantage on all Perception checks in darkness for 1 hour."},
    {id: 227, mishapname: "Eye of Despair", mishapeffect: "The caster sees a vision of a loved one suffering, causing them to take 1d6 psychic damage and giving disadvantage on concentration checks for 10 minutes."},
    {id: 228, mishapname: "Bone Hollowing", mishapeffect: "The caster’s bones ache, making them vulnerable to bludgeoning damage and imposing disadvantage on Strength checks for 1 hour."},
    {id: 229, mishapname: "Drained Vitality", mishapeffect: "The caster feels weakened, reducing their hit point maximum by 1d10 for 1d6 hours."},
    {id: 230, mishapname: "Unending Whispers", mishapeffect: "Unseen voices murmur in the caster’s mind, imposing disadvantage on concentration checks and Wisdom saving throws for 1d4 hours."},
    {id: 231, mishapname: "Skin of Stone", mishapeffect: "The caster’s skin hardens like stone, reducing Dexterity but granting resistance to slashing damage for 1d6 rounds."},
    {id: 232, mishapname: "Hollow Scream", mishapeffect: "The caster hears a scream echoing in their mind, taking 2d6 psychic damage and gaining disadvantage on Charisma checks for 10 minutes."},
    {id: 233, mishapname: "Grasping Shadows", mishapeffect: "Shadows cling to the caster’s form, halving their movement speed and giving disadvantage on Dexterity checks for 1 minute."},
    {id: 234, mishapname: "Fading Lifeforce", mishapeffect: "The caster’s life essence visibly dims, causing disadvantage on Charisma checks and reducing their hit points by 1d4 until they rest."},
    {id: 235, mishapname: "Unsettling Omen", mishapeffect: "Crows or other ominous animals gather around the caster, imposing disadvantage on all Charisma-based skill checks for 1 hour."},
    {id: 236, mishapname: "Veins of Darkness", mishapeffect: "Dark lines appear on the caster’s skin, imposing disadvantage on all saving throws involving Constitution for 1d4 hours."},
    {id: 237, mishapname: "Aura of Despair", mishapeffect: "A palpable sense of dread emanates from the caster, causing allies within 10 feet to suffer disadvantage on Wisdom saves for 1 minute."},
    {id: 238, mishapname: "Bleeding Eyes", mishapeffect: "The caster’s eyes begin to bleed, causing disadvantage on Perception checks and imposing 1d4 damage each round until healed."},
    {id: 239, mishapname: "Eldritch Mark", mishapeffect: "The caster gains an eerie tattoo that seems to move, marking them as cursed. This imposes disadvantage on all saving throws against magic for 1 hour."},
    {id: 240, mishapname: "Revenant’s Touch", mishapeffect: "The caster’s hand glows with necrotic energy, dealing 1d8 necrotic damage to any creature they touch for 1 minute."},
    {id: 241, mishapname: "Frozen Heart", mishapeffect: "The caster feels a numbing cold in their chest, reducing their Constitution and imposing disadvantage on saving throws against fear for 1d6 hours."},
    {id: 242, mishapname: "Unnatural Shadow", mishapeffect: "The caster’s shadow acts independently, creeping and shifting, which unnerves nearby creatures and imposes disadvantage on Charisma checks."},
    {id: 243, mishapname: "Spectral Chains", mishapeffect: "The caster feels spectral chains binding them, reducing movement by 15 feet and imposing disadvantage on Dexterity saves for 1 minute."},
    {id: 244, mishapname: "Cursed Wound", mishapeffect: "Any wound the caster receives bleeds uncontrollably, dealing 1d4 additional damage every round until tended."},
    {id: 245, mishapname: "Ravenous Hunger", mishapeffect: "The caster feels an insatiable hunger, imposing disadvantage on all concentration checks until they eat a full meal."},
    {id: 246, mishapname: "Twisted Limbs", mishapeffect: "The caster’s limbs contort painfully, giving disadvantage on all Dexterity checks and halving movement speed for 1d4 hours."},
    {id: 247, mishapname: "Hexed Speech", mishapeffect: "The caster’s voice sounds malicious, causing creatures to mistrust them and imposing disadvantage on all Persuasion checks for 1 hour."},
    {id: 248, mishapname: "Wraith’s Touch", mishapeffect: "For 1 minute, the caster’s touch feels chilling, dealing 1d6 cold damage to themselves each time they interact with objects or creatures."},
    {id: 249, mishapname: "Haunted Vision", mishapeffect: "The caster sees fleeting images of ghostly faces, imposing disadvantage on Perception checks for 1 hour."},
    {id: 250, mishapname: "Blighted Aura", mishapeffect: "Plants within 10 feet of the caster wilt and die, imposing disadvantage on Nature checks and making animals uneasy around them for 1 hour."},
    {id: 251, mishapname: "Demonic Imp", mishapeffect: "An imp appears, causing chaos and attacking nearby allies for 1d4 rounds before vanishing."},
    {id: 252, mishapname: "Swarm of Rats", mishapeffect: "A horde of feral rats emerges from nowhere, swarming the caster and dealing 1d4 piercing damage per round for 1 minute."},
    {id: 253, mishapname: "Vengeful Spirit", mishapeffect: "A ghostly figure of a long-dead warrior appears, seeking revenge. It attacks the caster once per round for 1 minute."},
    {id: 254, mishapname: "Shadow Beast", mishapeffect: "A shadowy creature manifests, obscuring the caster's vision and imposing disadvantage on all attack rolls for 1d4 minutes."},
    {id: 255, mishapname: "Wraith's Embrace", mishapeffect: "A wraith appears, attempting to drain the caster's life force, causing 1d8 necrotic damage. The caster must succeed on a DC 15 Constitution saving throw or be paralyzed for 1 minute."},
    {id: 256, mishapname: "Eldritch Horror", mishapeffect: "A small, tentacled creature bursts forth, causing madness. The caster must succeed on a DC 13 Wisdom saving throw or be frightened for 1 minute."},
    {id: 257, mishapname: "Cursed Wolf", mishapeffect: "A spectral wolf appears, howling ominously. It attacks the caster and has advantage on its attack rolls for 1 minute."},
    {id: 258, mishapname: "Minion of Madness", mishapeffect: "A small, maddened creature appears, spreading insanity. Each creature within 10 feet must succeed on a DC 14 Wisdom saving throw or be confused for 1 minute."},
    {id: 259, mishapname: "Ghastly Apparition", mishapeffect: "A ghast appears and siphons 1d6 hit points from the caster, who must succeed on a DC 15 Constitution saving throw to negate."},
    {id: 260, mishapname: "Fell Beast", mishapeffect: "A nightmarish creature appears, clawing at the caster. The caster takes 1d10 slashing damage and must succeed on a DC 14 Dexterity saving throw to avoid being knocked prone."},
    {id: 261, mishapname: "Spectral Hound", mishapeffect: "A ghostly hound appears, tracking the caster. It gives the caster disadvantage on all Stealth checks for 1 hour."},
    {id: 262, mishapname: "Bloodthirsty Swarm", mishapeffect: "A swarm of bloodsucking insects appears, dealing 1d4 damage every round until dispersed with fire or a strong wind."},
    {id: 263, mishapname: "Fiendish Familiar", mishapeffect: "A chaotic familiar appears and immediately attempts to sabotage the caster, imposing disadvantage on all spellcasting for 1 minute."},
    {id: 264, mishapname: "Mimic's Hunger", mishapeffect: "A mimic disguised as a nearby object opens up and attacks the caster, dealing 1d8 damage on a successful hit."},
    {id: 265, mishapname: "Chaos Elemental", mishapeffect: "An elemental of chaotic energy manifests, forcing the caster to succeed on a DC 14 Constitution saving throw or take 2d6 elemental damage."},
    {id: 266, mishapname: "Twisted Sprite", mishapeffect: "A malevolent sprite appears, enchanting the caster with an evil laugh. The caster must succeed on a DC 15 Wisdom saving throw or be charmed for 1 minute."},
    {id: 267, mishapname: "Phantom Flames", mishapeffect: "A ghostly fire spirit emerges, engulfing the caster in illusory flames, causing 1d6 psychic damage and leaving them frightened for 1 minute."},
    {id: 268, mishapname: "Dread Lurker", mishapeffect: "A horrifying creature emerges from the shadows, imposing disadvantage on the caster’s attack rolls for 1d4 minutes."},
    {id: 269, mishapname: "Vile Foliage", mishapeffect: "Unholy vines sprout from the ground, binding the caster and dealing 1d4 poison damage each round until they break free."},
    {id: 270, mishapname: "Horrific Clown", mishapeffect: "A grotesque clown appears, laughing maniacally and distracting the caster. The caster has disadvantage on Wisdom saves for 1 minute."},
    {id: 271, mishapname: "Banshee's Wail", mishapeffect: "A banshee's cry resonates, forcing all creatures within 30 feet to make a DC 15 Constitution saving throw or take 2d6 psychic damage and become frightened for 1 minute."},
    {id: 272, mishapname: "Wandering Horror", mishapeffect: "A creature composed of shifting shadows appears, making all creatures within 10 feet frightened for 1 minute."},
    {id: 273, mishapname: "Grim Sentry", mishapeffect: "A skeletal warrior emerges, attacking the caster once per round for 1 minute before vanishing."},
    {id: 274, mishapname: "Cursed Phantom", mishapeffect: "A ghostly figure appears, marking the caster for retribution. The next time they take damage, it is increased by 1d6."},
    {id: 275, mishapname: "Serpent of Nightmares", mishapeffect: "A dark serpent coils around the caster, dealing 1d8 psychic damage and imposing disadvantage on Constitution saves for 1 minute."},
    {id: 276, mishapname: "Cackling Harlequin", mishapeffect: "A mischievous harlequin appears, throwing daggers at the caster. The caster takes 1d6 piercing damage from the attack."},
    {id: 277, mishapname: "Doomed Familiar", mishapeffect: "A dark, ominous familiar appears, whispering dark prophecies that impose disadvantage on Wisdom saves for 1 hour."},
    {id: 278, mishapname: "Fallen Angel", mishapeffect: "A fallen angel appears, judging the caster. They must succeed on a DC 15 Charisma saving throw or take 1d10 radiant damage."},
    {id: 279, mishapname: "Gravewalker", mishapeffect: "A skeletal figure rises from the ground, imposing disadvantage on all Charisma checks for 1 hour."},
    {id: 280, mishapname: "Revenant's Call", mishapeffect: "A vengeful revenant appears, attacking the nearest creature to the caster. The revenant remains for 1 minute."},
    {id: 281, mishapname: "Vile Spirit", mishapeffect: "A tormented soul manifests, imposing disadvantage on the caster's spellcasting checks for 1 hour."},
    {id: 282, mishapname: "Shambling Horror", mishapeffect: "A grotesque creature lumbers forth, attacking the caster with a tendril for 1d6 bludgeoning damage."},
    {id: 283, mishapname: "Screaming Child", mishapeffect: "The disembodied spirit of a child appears, screaming in despair. The caster must succeed on a DC 14 Wisdom saving throw or take 1d6 psychic damage."},
    {id: 284, mishapname: "Flesh Golem", mishapeffect: "A creature made of stitched flesh appears, attempting to grapple the caster. On a success, it holds them for 1d4 rounds."},
    {id: 285, mishapname: "Ghostly Conductor", mishapeffect: "A spectral musician appears, playing a mournful tune. All creatures within 30 feet must make a DC 15 Wisdom saving throw or be incapacitated for 1 round."},
    {id: 286, mishapname: "Corpse Flower", mishapeffect: "A grotesque flower blooms at the caster’s feet, releasing spores that impose disadvantage on Constitution saves for 1 hour."},
    {id: 287, mishapname: "Spirit of the Forgotten", mishapeffect: "A ghostly figure lingers near the caster, sapping their strength and imposing disadvantage on all Strength checks for 1d4 hours."},
    {id: 288, mishapname: "Marionette of Malice", mishapeffect: "A dark puppet emerges, mimicking the caster’s movements. It imposes disadvantage on all attack rolls for 1 minute."},
    {id: 289, mishapname: "Cursed Doll", mishapeffect: "A creepy doll appears, cursing the caster. The caster takes 1d6 psychic damage every round until it is destroyed."},
    {id: 290, mishapname: "Nightmare Beast", mishapeffect: "A horrific creature appears, dragging the caster into a dreamscape. They must succeed on a DC 16 Wisdom saving throw or be incapacitated for 1 round."},
    {id: 291, mishapname: "Doomed Manticore", mishapeffect: "A manticore appears and immediately turns its attention to the caster, making a single attack against them."},
    {id: 292, mishapname: "Horrific Hydra", mishapeffect: "A small hydra appears, biting at the caster. It attacks once for 1d6 slashing damage before vanishing."},
    {id: 293, mishapname: "Gloomstalker", mishapeffect: "A creature of pure shadow lurks near the caster, giving them disadvantage on Stealth checks for 1d4 hours."},
    {id: 294, mishapname: "Lich's Minion", mishapeffect: "A skeletal minion appears, forced to do the caster’s bidding for 1 minute, but also attempts to drain 1d4 hit points from the caster."},
    {id: 295, mishapname: "Night Terror", mishapeffect: "A creature that feeds on fear appears, imposing disadvantage on all saving throws against fear for 1 hour."},
    {id: 296, mishapname: "Spectral Revenant", mishapeffect: "A ghostly revenant rises, dealing 1d8 necrotic damage and imposing disadvantage on Constitution saves for 1 hour."},
    {id: 297, mishapname: "Dread Vulture", mishapeffect: "A giant vulture appears, cawing loudly and giving disadvantage on all Perception checks for 1d4 hours."},
    {id: 298, mishapname: "Chained Horror", mishapeffect: "A creature with chains appears, grappling the caster and inflicting 1d6 bludgeoning damage each round until they escape."},
    {id: 299, mishapname: "Phantom Knight", mishapeffect: "A ghostly knight appears and challenges the caster to combat. If they refuse, they are frightened for 1d4 minutes."},
    {id: 300, mishapname: "Malefic Leech", mishapeffect: "A leech-like creature attaches itself to the caster, draining 1d4 hit points per round until removed."},
    {id: 301, mishapname: "Spirit of Retribution", mishapeffect: "A spectral figure appears and seeks vengeance, attacking the caster once for 1d6 necrotic damage."},
    {id: 302, mishapname: "Nightmare Rider", mishapeffect: "A spectral figure riding a nightmarish beast appears, imposing disadvantage on all Wisdom checks for 1 hour."},
    {id: 303, mishapname: "Skeletal Horse", mishapeffect: "A skeletal horse gallops in, causing the caster to take 1d4 bludgeoning damage from its weight."},
    {id: 304, mishapname: "Fey Trickster", mishapeffect: "A mischievous fey creature appears, causing confusion and imposing disadvantage on all Intelligence checks for 1 hour."},
    {id: 305, mishapname: "Tormented Child", mishapeffect: "The spirit of a lost child appears, crying and causing disadvantage on all Charisma saves for 1 hour."},
    {id: 306, mishapname: "Whispering Horror", mishapeffect: "A creature appears that whispers terrifying secrets, imposing disadvantage on Wisdom saves for 1 hour."},
    {id: 307, mishapname: "Undying Wretch", mishapeffect: "A zombie-like creature appears, attempting to grab the caster. If it succeeds, it drains 1d4 hit points per round."},
    {id: 308, mishapname: "Dreadful Faceless One", mishapeffect: "A faceless entity appears, stealing the caster's voice and imposing disadvantage on all communication checks for 1 hour."},
    {id: 309, mishapname: "Blood Wraith", mishapeffect: "A wraith made of blood appears, attempting to drain the caster’s vitality, dealing 1d6 necrotic damage."},
    {id: 310, mishapname: "Screaming Shade", mishapeffect: "A shade emerges, screaming in agony. All creatures within 20 feet must make a DC 15 Wisdom saving throw or take 1d6 psychic damage."},
    {id: 311, mishapname: "Doomed Beast", mishapeffect: "A grotesque creature emerges, causing panic. The caster must succeed on a DC 14 Wisdom saving throw or become frightened for 1 minute."},
    {id: 312, mishapname: "Spectral Giant", mishapeffect: "A spectral giant looms over the caster, causing them to take 1d8 psychic damage from its intimidating presence."},
    {id: 313, mishapname: "Cursed Gremlin", mishapeffect: "A gremlin appears, causing mechanical failure in any devices the caster uses for 1 hour."},
    {id: 314, mishapname: "Undead Fisherman", mishapeffect: "An undead fisherman appears, attempting to drown the caster. The caster must succeed on a DC 14 Strength saving throw or take 1d8 drowning damage."},
    {id: 315, mishapname: "Ravenous Spirit", mishapeffect: "A spirit appears, trying to consume the caster’s life essence, dealing 1d6 necrotic damage every round until dispelled."},
    {id: 316, mishapname: "Blighted Faerie", mishapeffect: "A blighted faerie appears, causing flora around the caster to wilt and imposing disadvantage on Nature checks for 1 hour."},
    {id: 317, mishapname: "Cursed Mariner", mishapeffect: "A cursed sailor appears, giving the caster disadvantage on all Navigation checks for 1 hour."},
    {id: 318, mishapname: "Dread Golem", mishapeffect: "A golem appears, filled with the essence of despair. It deals 1d10 bludgeoning damage on its first attack against the caster."},
    {id: 319, mishapname: "Plagued Beast", mishapeffect: "A creature infected with disease appears, forcing the caster to make a DC 15 Constitution saving throw or become poisoned for 1 hour."},
    {id: 320, mishapname: "Ghostly Abomination", mishapeffect: "A distorted figure appears, causing all creatures within 15 feet to take 1d6 psychic damage."},
    {id: 321, mishapname: "Chilling Shade", mishapeffect: "A chilling figure appears, causing the temperature to drop sharply. The caster must succeed on a DC 14 Constitution saving throw or take 1d4 cold damage."},
    {id: 322, mishapname: "Gloomfire Elemental", mishapeffect: "An elemental made of dark flames appears, dealing 1d8 fire damage to the caster."},
    {id: 323, mishapname: "Stygian Wyrm", mishapeffect: "A tiny wyrm made of shadows appears, imposing disadvantage on all Wisdom saves for 1 hour."},
    {id: 324, mishapname: "Gore Dancer", mishapeffect: "A creature that thrives on blood appears, causing the caster to bleed 1d4 hit points every round until healed."},
    {id: 325, mishapname: "Vengeful Spirit of the Past", mishapeffect: "A spirit from the caster's past appears, confronting them with unresolved guilt. The caster takes 1d6 psychic damage and must succeed on a DC 15 Wisdom saving throw or be frightened for 1 minute."},
    {id: 326, mishapname: "Ethereal Hunter", mishapeffect: "An ethereal creature manifests, following the caster. If the caster fails a saving throw, it can attack, dealing 1d8 necrotic damage."},
    {id: 327, mishapname: "Cursed Beast", mishapeffect: "A wild creature appears and attacks the caster, dealing 1d4 slashing damage on a successful hit."},
    {id: 328, mishapname: "Banshee's Cry", mishapeffect: "The cry of a banshee resonates, causing all creatures within 30 feet to make a DC 14 Constitution saving throw or take 2d6 psychic damage."},
    {id: 329, mishapname: "Wailing Specter", mishapeffect: "A wailing specter appears, forcing all creatures within 20 feet to make a DC 15 Wisdom saving throw or be frightened for 1 minute."},
    {id: 330, mishapname: "Cursed Koi", mishapeffect: "A malevolent fish appears, swimming around the caster. If the caster takes damage, they take an additional 1d4 psychic damage from the cursed fish’s presence."},
    {id: 331, mishapname: "Spectral Executioner", mishapeffect: "A ghostly executioner appears, declaring the caster’s guilt. The caster takes 1d10 necrotic damage and must succeed on a DC 15 Charisma saving throw or be frightened for 1 minute."},
    {id: 332, mishapname: "Lost Soul", mishapeffect: "A soul appears, lost and confused, causing disadvantage on all Charisma checks for 1 hour."},
    {id: 333, mishapname: "Grim Lurker", mishapeffect: "A lurking creature emerges from shadows, causing disadvantage on all Stealth checks for 1 hour."},
    {id: 334, mishapname: "Tormented Shade", mishapeffect: "A shade appears, tormenting the caster and imposing disadvantage on Wisdom saves for 1 hour."},
    {id: 335, mishapname: "Wretched Harbinger", mishapeffect: "A harbinger of doom appears, cursing the caster with misfortune, imposing disadvantage on all attack rolls for 1 hour."},
    {id: 336, mishapname: "Howling Specter", mishapeffect: "A howling spirit appears, causing the caster to take 1d6 psychic damage."},
    {id: 337, mishapname: "Veil of Shadows", mishapeffect: "A veil of darkness surrounds the caster, granting disadvantage on all Perception checks for 1 hour."},
    {id: 338, mishapname: "Whispering Horror", mishapeffect: "A creature whispers terrible secrets, causing the caster to take 1d4 psychic damage every round until they succeed on a DC 15 Wisdom saving throw."},
    {id: 339, mishapname: "Cursed Hag", mishapeffect: "A hag appears, cursing the caster. They must make a DC 16 Constitution saving throw or be cursed for 1 hour."},
    {id: 340, mishapname: "Twilight Wisp", mishapeffect: "A wisp appears, leading the caster astray. They must succeed on a DC 14 Intelligence saving throw or wander off for 1 hour."},
    {id: 341, mishapname: "Eldritch Guardian", mishapeffect: "An eldritch creature appears, giving the caster disadvantage on all attack rolls for 1d4 rounds."},
    {id: 342, mishapname: "Necrotic Shade", mishapeffect: "A necrotic shade appears, imposing disadvantage on all Constitution saves for 1 hour."},
    {id: 343, mishapname: "Phantom Stalker", mishapeffect: "A phantom creature appears and shadows the caster, imposing disadvantage on all Dexterity checks for 1 hour."},
    {id: 344, mishapname: "Creeping Dread", mishapeffect: "A creature of fear appears, giving the caster disadvantage on all saves against fear for 1 hour."},
    {id: 345, mishapname: "Blighted Mantis", mishapeffect: "A large, blighted mantis appears, attacking the caster and dealing 1d4 slashing damage."},
    {id: 346, mishapname: "Shattered Soul", mishapeffect: "A creature that feeds on shattered souls appears, causing the caster to take 1d6 necrotic damage and imposing disadvantage on all saving throws for 1 hour."},
    {id: 347, mishapname: "Cursed Behemoth", mishapeffect: "A massive creature appears, crushing nearby objects. The caster takes 1d8 bludgeoning damage on its first attack."},
    {id: 348, mishapname: "Chilling Phantasm", mishapeffect: "A chilling phantom appears, imposing disadvantage on all Wisdom saving throws for 1 hour."},
    {id: 349, mishapname: "Twisted Watcher", mishapeffect: "A twisted figure watches the caster, imposing disadvantage on all Charisma checks for 1 hour."},
    {id: 350, mishapname: "Grim Harvester", mishapeffect: "A grim creature appears, causing all creatures within 10 feet to take 1d6 necrotic damage."},
    {id: 351, mishapname: "Ominous Oozeling", mishapeffect: "A small, sentient ooze appears, attempting to cling to the caster and deal 1d4 acid damage each round until removed."},
    {id: 352, mishapname: "Whispering Hound", mishapeffect: "A ghostly hound appears, attempting to bite the caster, dealing 1d6 damage and giving them disadvantage on Wisdom saves for 1 minute."},
    {id: 353, mishapname: "Eldritch Snare", mishapeffect: "A snare of eldritch energy binds the caster, dealing 1d4 psychic damage every round until they break free."},
    {id: 354, mishapname: "Vile Apparition", mishapeffect: "An apparition of a long-dead villain appears, imposing disadvantage on all attack rolls for 1 minute."},
    {id: 355, mishapname: "Dread Spawn", mishapeffect: "A creature spawned from nightmares appears, dealing 1d8 psychic damage to the caster and imposing disadvantage on Constitution saves for 1 hour."},
    {id: 356, mishapname: "Harbinger of Chaos", mishapeffect: "A chaotic creature appears, forcing the caster to make a DC 15 Intelligence saving throw or take 1d6 chaos damage."},
    {id: 357, mishapname: "Ruinous Shade", mishapeffect: "A shade of ruin appears, dealing 1d8 necrotic damage to the caster and imposing disadvantage on all saving throws for 1 hour."},
    {id: 358, mishapname: "Cursed Scavenger", mishapeffect: "A scavenging creature appears, causing the caster to take 1d4 damage from its greedy attacks."},
    {id: 359, mishapname: "Sorrowful Wraith", mishapeffect: "A wraith appears, causing the caster to take 1d6 necrotic damage and imposing disadvantage on Wisdom saves for 1 hour."},
    {id: 360, mishapname: "Spectral Carrion", mishapeffect: "A spectral carrion beast appears, inflicting 1d8 necrotic damage and imposing disadvantage on all Constitution checks for 1 hour."},
    {id: 361, mishapname: "Shadowy Puppeteer", mishapeffect: "A creature that pulls the strings of shadow appears, forcing the caster to move unpredictably for 1 minute, giving disadvantage on Dexterity checks."},
    {id: 362, mishapname: "Cursed Scarecrow", mishapeffect: "A sinister scarecrow appears, striking fear into the caster's heart, imposing disadvantage on all Charisma saves for 1 hour."},
    {id: 363, mishapname: "Twisted Inquisitor", mishapeffect: "An inquisitor of the night appears, interrogating the caster, imposing disadvantage on all Intelligence checks for 1 hour."},
    {id: 364, mishapname: "Wailing Sorrow", mishapeffect: "A sorrowful creature appears, causing the caster to take 1d4 psychic damage and imposing disadvantage on Wisdom saves for 1 hour."},
    {id: 365, mishapname: "Abysmal Golem", mishapeffect: "A golem formed from the essence of despair appears, dealing 1d10 necrotic damage to the caster."},
    {id: 366, mishapname: "Forgotten Revenant", mishapeffect: "A revenant lost to time appears, attacking the caster for 1d8 necrotic damage."},
    {id: 367, mishapname: "Ghastly Yowler", mishapeffect: "A ghast appears, yowling in agony. All creatures within 30 feet must make a DC 14 Constitution saving throw or take 1d6 necrotic damage."},
    {id: 368, mishapname: "Creeping Dread", mishapeffect: "A creature that feeds on dread appears, imposing disadvantage on all Constitution checks for 1 hour."},
    {id: 369, mishapname: "Ravenous Fiend", mishapeffect: "A small fiend appears, attempting to steal the caster's hit points. The caster takes 1d4 necrotic damage and must succeed on a DC 15 Constitution saving throw or take additional damage."},
    {id: 370, mishapname: "Sorrowful Wight", mishapeffect: "A wight appears, dealing 1d6 necrotic damage and giving the caster disadvantage on Constitution saves for 1 hour."},
    {id: 371, mishapname: "Cursed Collector", mishapeffect: "A collector of souls appears, attempting to siphon the caster's life force, dealing 1d4 damage each round until dispelled."},
    {id: 372, mishapname: "Doomed Revenant", mishapeffect: "A revenant of a long-dead hero appears, seeking vengeance. The caster must make a DC 15 Wisdom saving throw or take 1d10 radiant damage."},
    {id: 373, mishapname: "Eldritch Beast", mishapeffect: "A creature of pure chaos appears, dealing 1d6 damage on its first attack and imposing disadvantage on all attack rolls for 1 minute."},
    {id: 374, mishapname: "Chilling Specter", mishapeffect: "A specter appears, causing the temperature to drop. The caster takes 1d4 cold damage and has disadvantage on Dexterity checks for 1 hour."},
    {id: 375, mishapname: "Ravenous Siphoner", mishapeffect: "A siphoning creature appears, draining the caster's energy and dealing 1d4 necrotic damage every round until defeated."},
    {id: 376, mishapname: "Cursed Grasp", mishapeffect: "A grasping creature appears, attempting to immobilize the caster. The caster must succeed on a DC 14 Strength saving throw or be restrained for 1 minute."},
    {id: 377, mishapname: "Fell Harbinger", mishapeffect: "A harbinger of doom appears, forcing the caster to take 1d6 psychic damage and imposing disadvantage on all saving throws for 1 hour."},
    {id: 378, mishapname: "Nightmare Beast", mishapeffect: "A nightmare creature appears, causing fear and imposing disadvantage on Wisdom saves for 1 hour."},
    {id: 379, mishapname: "Horrific Abomination", mishapeffect: "An abomination made of flesh and bone appears, dealing 1d8 slashing damage on its first attack."},
    {id: 380, mishapname: "Ominous Wight", mishapeffect: "A wight emerges, imposing disadvantage on all Constitution saves for 1 hour."},
    {id: 381, mishapname: "Tormented Fiend", mishapeffect: "A tormented fiend appears, dealing 1d6 damage on its first attack and giving disadvantage on all saving throws for 1 hour."},
    {id: 382, mishapname: "Malevolent Shade", mishapeffect: "A malevolent shade appears, imposing disadvantage on all Wisdom checks for 1 hour."},
    {id: 383, mishapname: "Wretched Maw", mishapeffect: "A maw filled with teeth appears, attempting to bite the caster for 1d4 damage on a successful attack."},
    {id: 384, mishapname: "Vile Apparition", mishapeffect: "A vile spirit appears, cursing the caster and imposing disadvantage on all attack rolls for 1 hour."},
    {id: 385, mishapname: "Dreadful Gloom", mishapeffect: "A creature of darkness appears, giving the caster disadvantage on all saving throws for 1 hour."},
    {id: 386, mishapname: "Spectral Beast", mishapeffect: "A spectral creature emerges, causing fear. The caster must succeed on a DC 15 Wisdom saving throw or take 1d6 psychic damage."},
    {id: 387, mishapname: "Sorrowing Wraith", mishapeffect: "A wraith appears, imposing disadvantage on all attack rolls for 1 hour."},
    {id: 388, mishapname: "Ghostly Hunter", mishapeffect: "A ghostly hunter appears, targeting the nearest creature. The caster takes 1d6 damage if they attempt to intervene."},
    {id: 389, mishapname: "Chained Nightmare", mishapeffect: "A creature bound in chains appears, attempting to grapple the caster. If it succeeds, it drains 1d4 hit points per round."},
    {id: 390, mishapname: "Tormented Vengeance", mishapeffect: "A creature seeking vengeance appears, dealing 1d6 necrotic damage on its first attack."},
    {id: 391, mishapname: "Cursed Wraith", mishapeffect: "A wraith appears, imposing disadvantage on all Wisdom checks for 1 hour."},
    {id: 392, mishapname: "Harbinger of Despair", mishapeffect: "A creature that embodies despair appears, causing the caster to take 1d8 psychic damage and giving them disadvantage on all saving throws for 1 hour."},
    {id: 393, mishapname: "Vengeful Shade", mishapeffect: "A vengeful shade appears, dealing 1d6 necrotic damage on its first attack and imposing disadvantage on all saving throws for 1 hour."},
    {id: 394, mishapname: "Chilling Wraith", mishapeffect: "A wraith of ice appears, dealing 1d8 cold damage and imposing disadvantage on all Dexterity saves for 1 hour."},
    {id: 395, mishapname: "Malevolent Spirit", mishapeffect: "A malevolent spirit appears, draining the caster's energy. The caster must succeed on a DC 15 Constitution saving throw or take 1d4 necrotic damage every round until dispelled."},
    {id: 396, mishapname: "Doomed Phantom", mishapeffect: "A phantom appears, attempting to drain the caster’s vitality, dealing 1d4 necrotic damage."},
    {id: 397, mishapname: "Spectral Revenant", mishapeffect: "A revenant appears, imposing disadvantage on all Charisma checks for 1 hour."},
    {id: 398, mishapname: "Gravewalker Spirit", mishapeffect: "A spirit from the grave appears, causing the caster to take 1d6 necrotic damage and imposing disadvantage on all Constitution saves for 1 hour."},
    {id: 399, mishapname: "Eldritch Horror", mishapeffect: "A small creature of pure madness appears, causing the caster to take 1d8 psychic damage and imposing disadvantage on all saving throws for 1 hour."},
    {id: 400, mishapname: "Cursed Undead", mishapeffect: "An undead creature appears, giving the caster disadvantage on all Wisdom checks for 1 hour."},
    {id: 401, mishapname: "Ruinous Beast", mishapeffect: "A beast made of ruin appears, imposing disadvantage on all Dexterity saves for 1 hour."},
    {id: 402, mishapname: "Howling Spirit", mishapeffect: "A howling spirit appears, imposing disadvantage on all Constitution saves for 1 hour."},
    {id: 403, mishapname: "Twisted Abomination", mishapeffect: "An abomination of flesh appears, dealing 1d6 slashing damage on its first attack."},
    {id: 404, mishapname: "Wailing Entity", mishapeffect: "An entity that wails appears, imposing disadvantage on all Wisdom checks for 1 hour."},
    {id: 405, mishapname: "Cursed Guardian", mishapeffect: "A guardian of the cursed appears, attempting to restrain the caster. The caster must succeed on a DC 14 Strength saving throw or be restrained for 1 minute."},
    {id: 406, mishapname: "Phantom Menace", mishapeffect: "A phantom creature appears, targeting the caster. They take 1d4 psychic damage and have disadvantage on all saving throws for 1 hour."},
    {id: 407, mishapname: "Tormented Fury", mishapeffect: "A furious spirit appears, dealing 1d8 damage on its first attack and imposing disadvantage on all attack rolls for 1 minute."},
    {id: 408, mishapname: "Wretched Shade", mishapeffect: "A shade of despair appears, causing the caster to take 1d4 necrotic damage and imposing disadvantage on all Wisdom checks for 1 hour."},
    {id: 409, mishapname: "Vengeful Wight", mishapeffect: "A wight appears, imposing disadvantage on all Charisma checks for 1 hour."},
    {id: 410, mishapname: "Ravenous Shadow", mishapeffect: "A shadow appears, attempting to drain the caster’s life force, dealing 1d6 necrotic damage on its first attack."},
    {id: 411, mishapname: "Sorrowing Apparition", mishapeffect: "An apparition of sorrow appears, dealing 1d4 psychic damage every round until dispelled."},
    {id: 412, mishapname: "Fell Haunting", mishapeffect: "A haunting creature appears, causing the caster to take 1d6 damage and imposing disadvantage on all saving throws for 1 hour."},
    {id: 413, mishapname: "Grim Shade", mishapeffect: "A shade of grim fate appears, imposing disadvantage on all Constitution checks for 1 hour."},
    {id: 414, mishapname: "Cursed Phantom", mishapeffect: "A phantom appears, dealing 1d4 necrotic damage and imposing disadvantage on all saving throws for 1 hour."},
    {id: 415, mishapname: "Harrowing Spector", mishapeffect: "A specter appears, causing disadvantage on all Intelligence checks for 1 hour."},
    {id: 416, mishapname: "Cursed Revenant", mishapeffect: "A revenant of a long-dead warrior appears, seeking revenge. The caster takes 1d8 necrotic damage on its first attack."},
    {id: 417, mishapname: "Tormented Spirit", mishapeffect: "A spirit appears, imposing disadvantage on all saving throws for 1 hour."},
    {id: 418, mishapname: "Gravekeeper Wight", mishapeffect: "A wight appears, giving the caster disadvantage on all Charisma checks for 1 hour."},
    {id: 419, mishapname: "Despairing Shade", mishapeffect: "A shade that feeds on despair appears, dealing 1d6 necrotic damage to the caster."},
    {id: 420, mishapname: "Harbinger of Nightmares", mishapeffect: "A creature that brings nightmares appears, imposing disadvantage on all Constitution saves for 1 hour."},
    {id: 421, mishapname: "Wretched Revenant", mishapeffect: "A revenant appears, seeking vengeance. The caster must succeed on a DC 14 Wisdom saving throw or take 1d8 necrotic damage."},
    {id: 422, mishapname: "Spectral Hunter", mishapeffect: "A spectral hunter appears, dealing 1d6 necrotic damage on its first attack and imposing disadvantage on all Dexterity checks for 1 hour."},
    {id: 423, mishapname: "Fallen Guardian", mishapeffect: "A fallen guardian appears, attempting to restrain the caster. They must succeed on a DC 14 Strength saving throw or be restrained for 1 minute."},
    {id: 424, mishapname: "Cursed Horror", mishapeffect: "A horror from the abyss appears, causing the caster to take 1d4 psychic damage and imposing disadvantage on all Wisdom checks for 1 hour."},
    {id: 425, mishapname: "Spectral Executioner", mishapeffect: "A ghostly executioner appears, dealing 1d8 necrotic damage on its first attack."},
    {id: 426, mishapname: "Doomed Shade", mishapeffect: "A shade appears, imposing disadvantage on all Constitution saves for 1 hour."},
    {id: 427, mishapname: "Tormented Revenant", mishapeffect: "A revenant appears, seeking vengeance, dealing 1d6 necrotic damage on its first attack."},
    {id: 428, mishapname: "Grim Wight", mishapeffect: "A wight appears, imposing disadvantage on all Charisma checks for 1 hour."},
    {id: 429, mishapname: "Chilling Wight", mishapeffect: "A wight of ice appears, dealing 1d4 cold damage and imposing disadvantage on all Dexterity saves for 1 hour."},
    {id: 430, mishapname: "Cursed Spirit", mishapeffect: "A spirit appears, attempting to drain the caster’s life essence, dealing 1d6 necrotic damage each round until defeated."},
    {id: 431, mishapname: "Sorrowful Revenant", mishapeffect: "A revenant appears, dealing 1d4 necrotic damage and imposing disadvantage on all Wisdom checks for 1 hour."},
    {id: 432, mishapname: "Veil of Sorrow", mishapeffect: "A veil of sorrow surrounds the caster, imposing disadvantage on all Charisma checks for 1 hour."},
    {id: 433, mishapname: "Dreadful Spirit", mishapeffect: "A dreadful spirit appears, causing the caster to take 1d4 damage and imposing disadvantage on all saving throws for 1 hour."},
    {id: 434, mishapname: "Chained Tormentor", mishapeffect: "A tormentor bound by chains appears, dealing 1d4 psychic damage every round until they escape."},
    {id: 435, mishapname: "Cursed Soul", mishapeffect: "A soul appears, causing the caster to take 1d4 necrotic damage and imposing disadvantage on all saving throws for 1 hour."},
    {id: 436, mishapname: "Grim Specter", mishapeffect: "A grim specter appears, imposing disadvantage on all Intelligence checks for 1 hour."},
    {id: 437, mishapname: "Phantom of Agony", mishapeffect: "A phantom appears, dealing 1d8 psychic damage to the caster and imposing disadvantage on all saving throws for 1 hour."},
    {id: 438, mishapname: "Despairing Revenant", mishapeffect: "A revenant appears, dealing 1d4 necrotic damage and imposing disadvantage on all Wisdom saves for 1 hour."},
    {id: 439, mishapname: "Eldritch Fiend", mishapeffect: "A fiend of pure chaos appears, attempting to drain the caster’s hit points. The caster must succeed on a DC 15 Constitution saving throw or take 1d8 necrotic damage."},
    {id: 440, mishapname: "Vile Spirit", mishapeffect: "A spirit appears, dealing 1d6 necrotic damage and imposing disadvantage on all Wisdom saves for 1 hour."},
    {id: 441, mishapname: "Wailing Dread", mishapeffect: "A creature that wails appears, causing all creatures within 30 feet to take 1d6 psychic damage."},
    {id: 442, mishapname: "Cursed Abomination", mishapeffect: "An abomination of dread appears, dealing 1d8 necrotic damage and imposing disadvantage on all Constitution checks for 1 hour."},
    {id: 443, mishapname: "Ghostly Revenant", mishapeffect: "A revenant appears, seeking revenge. The caster must succeed on a DC 14 Wisdom saving throw or take 1d6 necrotic damage."},
    {id: 444, mishapname: "Tormented Wight", mishapeffect: "A wight appears, imposing disadvantage on all Charisma checks for 1 hour."},
    {id: 445, mishapname: "Sorrowing Phantom", mishapeffect: "A phantom appears, causing the caster to take 1d6 damage and imposing disadvantage on all saving throws for 1 hour."},
    {id: 446, mishapname: "Chilling Apparition", mishapeffect: "An apparition appears, imposing disadvantage on all Dexterity checks for 1 hour."},
    {id: 447, mishapname: "Fell Revenant", mishapeffect: "A revenant appears, seeking vengeance, dealing 1d8 necrotic damage on its first attack."},
    {id: 448, mishapname: "Spectral Wraith", mishapeffect: "A wraith appears, dealing 1d6 damage on its first attack and imposing disadvantage on all Wisdom saves for 1 hour."},
    {id: 449, mishapname: "Grim Shade", mishapeffect: "A shade appears, imposing disadvantage on all Constitution saves for 1 hour."},
    {id: 450, mishapname: "Eldritch Terror", mishapeffect: "A creature of pure madness appears, dealing 1d10 psychic damage on its first attack."},
   
];

function getRandomMishap() {
    const randomIndex = Math.floor(Math.random() * MishapTable.length);
    const mishap = MishapTable[randomIndex];
    return `<span class="mishap-name"><strong>${mishap.mishapname}</strong>:</span> <span class="mishap-effect">${mishap.mishapeffect}</span>`;
}

document.getElementById("generateMishapButton").addEventListener("click", function () {
  const mishap = getRandomMishap();
  document.getElementById("result").innerHTML = `
    <div class="mishap">
      <p>${mishap}</p>
    </div>
  `;
});